### ISSUE TITLE
Building with gcc-13 or clang-19 doesn't work. Gives the error `format` File not found

### ISSUE THREAD

**Issue by lokitkhemka** [Jaysmito101/Xlux#2]
I was trying to build this project on Pop OS 22.04 and it gives me the error that `format header is not found`. I upgraded to `gcc` to version `13.1.0`. I even tried with `clang` version `19.1.1`.

Can you please help me with it? Thank you.

**Comment by Jaysmito101** [comment]
Does that version have full support of C++20? I remember facing a similar issue because of that. std::format and std::vfromat seems to be not there in some compiler versions with partial C++20 support

**Comment by lokitkhemka** [comment]
I got it running with Visual Studio 2022.
