### ISSUE TITLE
Where can I download the asset files?

### ISSUE THREAD

**Issue by lokitkhemka** [Jaysmito101/Xlux#3]
Hi,

I need the assets files to run the programs. Can you point me to where I can download them from?

Thank you.

**Comment by Jaysmito101** [comment]
I dont remember the sources for all but here are the ones I do remember:

Model Loading: https://sketchfab.com/3d-models/super-human-7aa58e978b9f4357b8e73d8e0440c896
PBR one : https://sketchfab.com/3d-models/nile-42e02439c61049d681c897441d40aaa1
